name: cicd
on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: only-one

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        # BuildKit (used with `docker buildx`) is the best way to build images
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: rafarlopes/cicd-example
          flavor: latest=true
          tags: |
            type=sha,enable=true,priority=100,prefix=,suffix=,format=short
      -
        # this will build the images, once per platform,
        # then push to one or more registries (based on image list above in docker_meta)
        name: Docker Build and Push
        id: build_image
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          # it uses github cache API for faster builds:
          # https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#cache-backend-api
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
